catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'catalog'


urlpatterns = [
    path('', cache_page(60)(views.ProductsListView.as_view()), name='product_list'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('product/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_page'),
    path('product/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),

    path('blog/', views.BlogListView.as_view(), name='blog_list'),
    path('blog/create/', views.BlogCreateView.as_view(), name='blog_create'),
    path('blog/<slug:slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('blog/<slug:slug>/update/', views.BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<slug:slug>/update/', views.BlogDeleteView.as_view(), name='blog_delete')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, ProfileView, WaitActivationView, EmailVerificationView, UserPasswordResetView

app_name = 'users'

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/whait', WaitActivationView.as_view(), name='wait_activation'),
    path('verify-email/', EmailVerificationView.as_view(), name='verify_email'),
    path('reset-password/', UserPasswordResetView.as_view(), name='reset_password'),
    path('profile/', ProfileView.as_view(), name='profile')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None

    email = models.EmailField(verbose_name='Email', unique=True)

    avatar = models.ImageField(upload_to='users/', verbose_name='Avatar', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='Phone number', **NULLABLE)
    country = models.CharField(max_length=235, verbose_name='Country', **NULLABLE)
    email_verification_token = models.CharField(max_length=235, verbose_name='Токен верификации')
    is_verified = models.BooleanField(default=False, **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.mail import send_mail

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import string
import random

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:wait_activation')

    def send_email(self, user, token):
        send_mail(
            'Подтверждение регистрации',
            f'{self.request.build_absolute_uri(reverse("users:verify_email"))}?token={token}',
            settings.EMAIL_HOST_USER,
            [user.email]
        )

    def form_valid(self, form):
        user = form.save(commit=False)
        token = default_token_generator.make_token(user)
        user.email_verification_token = token
        self.send_email(user, token)
        user.save()
        return super().form_valid(form)


class EmailVerificationView(View):
    def get(self, request, *args, **kwargs):
        token = request.GET.get('token')
        user = get_object_or_404(User, email_verification_token=token)
        user.is_verified = True
        user.save()
        return redirect('users:login')
# asdad__dasdrf334


class WaitActivationView(TemplateView):
    template_name = 'users/activation.html'


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordResetView(View):
    def send_password(self, user, password):
        send_mail(
            'Новый пароль',
            f'{password}',
            settings.EMAIL_HOST_USER,
            [user.email]
        )

    def get(self, request, *args, **kwargs):
        user = self.request.user
        print(user._meta)
        if user.is_authenticated:
            password = ''.join(random.choices(string.ascii_letters + string.digits, k=10))
            print(user._meta)
            self.send_password(user, password)
            print(user._meta)
            user.set_password(password)
            print(user._meta)
            user.save()
        return redirect('users:login')

users/templates/users/activation.html
{% extends 'catalog/base.html' %}
{% block content %}

    <style>
    .card {
        background-color: #222022;
    }
    form {
        color: white;
    }
    form input[type="text"],
    form textarea {
        width: 100%;
    }
    </style>

    <div class="container">
        <div class="row text-center">
            <p class="lead" style="color: white" ;>На указанную почту отправлено письмо. Перейдите по ссылке из письма</p>
        </div>
    </div>

{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}

    <style>
    .card {
        background-color: #222022;
    }
    form {
        color: white;
    }
    form input[type="text"],
    form textarea {
        width: 100%;
    }
    </style>

    <div class="container">
        <div class="row text-center">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Войти</button>
                    <a href="{% url 'users:reset_password' %}" class="btn btn-primary">Сбросить пароль</a>
                    <a href="{% url 'catalog:product_list' %}" class="btn btn-primary">Назад</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% block content %}

    <style>
    .card {
        background-color: #222022;
    }
    form {
        color: white;
    }
    form input[type="text"],
    form textarea {
        width: 100%;
    }
    </style>

    <div class="container">
        <div class="row text-center">
            <div class="col-3"></div>
                <div class="card mb-4 box-shadow">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Регистрация</button>
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-primary">Назад</a>
                    </form>
                </div>
        </div>
    </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content %}

    <style>
    .card {
        background-color: #222022;
    }
    form {
        color: white;
    }
    form input[type="text"],
    form textarea {
        width: 100%;
    }
    </style>

    <div class="container">
        <div class="row text-center">
            <div class="col-3"></div>
                <div class="card mb-4 box-shadow">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <a type="button" class="btn btn-primary" href="{% url 'users:reset_password' %}">Создать новый пароль</a>
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-primary">Назад</a>
                    </form>
                </div>
        </div>
    </div>

{% endblock %}