catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'catalog'


urlpatterns = [
    path('', cache_page(60)(views.ProductsListView.as_view()), name='product_list'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('product/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_page'),
    path('product/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),

    path('blog/', views.BlogListView.as_view(), name='blog_list'),
    path('blog/create/', views.BlogCreateView.as_view(), name='blog_create'),
    path('blog/<slug:slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('blog/<slug:slug>/update/', views.BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<slug:slug>/update/', views.BlogDeleteView.as_view(), name='blog_delete')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, ProfileView, WaitActivationView, EmailVerificationView, UserPasswordResetView

app_name = 'users'

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/whait', WaitActivationView.as_view(), name='wait_activation'),
    path('verify-email/', EmailVerificationView.as_view(), name='verify_email'),
    path('reset-password/', UserPasswordResetView.as_view(), name='reset_password'),
    path('profile/', ProfileView.as_view(), name='profile')
]

catalog/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils import timezone
from pytils.translit import slugify

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.name}, {self.description}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('created_at',)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    preview = models.ImageField(upload_to='product/', verbose_name='Превью')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='Цена')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    is_published = models.BooleanField(verbose_name='Опубликовано', default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.description}'

    def save(self, *args, **kwargs):
        return super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.is_published = False
        self.save()

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('created_at',)


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.SlugField(unique=True)
    content = models.TextField(verbose_name='Сообщение')
    image = models.ImageField(upload_to='blog/', verbose_name='Превью', blank=False)
    create_date = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    is_published = models.BooleanField(verbose_name='Опубликовано', default=True)
    count_views = models.IntegerField(verbose_name='Количество просмотров', default=0)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(self.title)
            num = 1
            for blog in Blog.objects.all():
                if blog.slug == slug:
                    slug = f'{slug}_{num}'
                    num += 1
            self.slug = slug
        return super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.is_published = False
        self.save()

    def get_absolute_url(self):
        return reverse("blog_detail", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = 'Пост блога'
        verbose_name_plural = 'Посты блога'
        ordering = ['create_date']


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    version_number = models.CharField(max_length=50)
    version_name = models.CharField(max_length=100)
    is_current = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.product} - {self.version_name}"

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

catalog/forms.py
from django import forms
from catalog.models import Blog, Product, Version
from django.forms import formset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', 'image',)


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ('version_name',)


class ProductForm(forms.ModelForm):
    versions = formset_factory(VersionForm, extra=1)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('name', css_class='form-control'),
            Field('description', css_class='form-control'),
            Field('preview', css_class='form-control'),
            Field('category', css_class='form-control'),
            Field('price', css_class='form-control'),
            Field('Versions', css_class='form-control'),
        )

    class Meta:
        model = Product
        fields = ("name", "description", "preview", "category", "price")


    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name', '')
        description = cleaned_data.get('description', '')

        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']

        for word in forbidden_words:
            if word in name.lower() or word in description.lower():
                raise forms.ValidationError("Недопустимое содержимое в названии или описании продукта.")

        versions = cleaned_data.get('versions')
        if versions:
            for version_form in versions:
                if not version_form.is_valid():
                    raise forms.ValidationError("Недопустимое содержимое в версии продукта.")
        return cleaned_data

    def save_versions(self, product):
        versions = self.cleaned_data.get('versions')
        if versions:
            for version_form in versions:
                version = version_form.save(commit=False)
                version.product = product
                version.save()

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from catalog.models import Product, Blog, Version
from django.views import generic
from django.urls import reverse_lazy, reverse
from catalog.forms import BlogForm, ProductForm, VersionForm
from django.forms import inlineformset_factory


class ContactView(generic.TemplateView):
    template_name = 'catalog/contacts.html'


class ProductsListView(generic.ListView):
    model = Product
    context_object_name = 'products'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        active_versions = Version.objects.filter(is_current=True).select_related('product')
        context['active_versions'] = active_versions
        return context


class ProductDetailView(generic.DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, generic.CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        form.instance.user = self.request.user
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def test_func(self):
        return self.request.user == self.get_object().user

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        form.instance.user = self.request.user
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def test_func(self):
        return self.request.user == self.get_object().user


class BlogListView(generic.ListView):
    model = Blog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(generic.DetailView):
    model = Blog
    slug_url_kwarg = 'slug'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object.count_views += 1
        self.object.save()
        return context


class BlogCreateView(generic.CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('catalog:blog_list')

    def form_valid(self, form):
        response = super().form_valid(form)
        return response


class BlogUpdateView(generic.UpdateView):
    model = Blog
    form_class = BlogForm

    def form_valid(self, form):
        response = super().form_valid(form)
        return response

    def get_success_url(self):
        return reverse('catalog:blog_detail', kwargs={'slug': self.object.slug})


class BlogDeleteView(generic.DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Это вам на руку</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/base_custom.css" rel="stylesheet">
    <link href="/static/css/home_custom.css" rel="stylesheet">

</head>
<body>
<header>
    <div>
        <h5 class="main_header">Это вам на руку</h5>
        <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
            <a class="p-2 btn btn-outline-primary" href="/contact/">Контакты</a>
            <a class="p-2 btn btn-outline-primary" href="/blog">БлоХ</a>
            {% if user.is_authenticated %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}" style="float: right; margin-right: 10px;">Выйти</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}" style="float: right; margin-right: 10px;">Профиль</a>
            {% else %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}" style="float: right; margin-right: 10px;">Войти</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}" style="float: right; margin-right: 10px;">Регистрация</a>
            {% endif %}
        </nav>
    </div>
</header>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4";>Это вам на руку</h1>
    <p class="lead";>Это вам на руку - магазин наручных часов и не только</p>
</div>

<div class="container">
    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md" style="color: white">
                Это вам на руку
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load catalog_tags %}

    <style>
    .card {
        background-color: #222022;
    }
    form {
        color: white;
    }
    form input[type="text"],
    form textarea {
        width: 100%;
    }
    </style>

    <div class="container">
        <div class="row text-center">
            <div class="col-xxl-50">
                <div class="card mb-4 box-shadow">
                    <form method="post">
                        {% csrf_token %}
                        Удаляем?
                        <input type='submit' class="btn btn-danger" value="Да">
                        <a href="{% url 'catalog:blog_list' %}" class="btn btn-primary">Назад</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load catalog_tags %}

    <div class="container">
        <div class="row text-center">
            <div class="col-xxl-50">
                <div class="card mb-4 box-shadow">
                    <div class="card-header d-flex align-items-center justify-content-center" style="height: 100px">
                      <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    </div>
                    <div class="card-body">
                        <p class="text-center">Просмотров {{ object.count_views }}</p>
                        <img src="{{ object.image|mediapath }}" alt="Превью картинки" style="max-width: 100%; width: 600px; height: 600px">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <p class="text-center">{{ object.content }}</p>
                        </ul>
                        <a href="{% url 'blog_update' slug=object.slug %}" class="btn btn-primary">Редактировать</a>
                        <a href="{% url 'blog_delete' slug=object.slug %}" class="btn btn-primary">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load catalog_tags %}

    <style>
    .card {
        background-color: #222022;
    }
    form {
        color: white;
    }
    form input[type="text"],
    form textarea {
        width: 100%;
    }
    </style>

    <div class="container">
        <div class="row text-center">
            <div class="col-xxl-50">
                <div class="card mb-4 box-shadow">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <a href="{% url 'blog_list' %}" class="btn btn-primary">Назад</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load catalog_tags %}

<div class="container">
    <div class="row text-center">
        <a href="/blog/create/" class="btn btn-lg btn-block btn-outline-primary">Создать новую запись</a>
        {% for el in object_list %}
            <div class="col-3 mt-4">
                <a href="/blog/{{el.slug}}" style="text-decoration: none; color: black">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header d-flex align-items-center justify-content-center" style="height: 100px">
                          <h4 class="my-0 font-weight-normal">{{ el.title }}</h4>
                        </div>
                        <div class="card-body">
                            <img src="{{ el.image|mediapath }}" alt="Превью картинки" style="max-width: 100%;">
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <p>{% if el.content|length <= 50 %}
                                        <li>{{ el.content }}</li>
                                    {% else %}
                                        <li>{{ el.content|slice:":50" }}...</li>
                                    {% endif %}
                                </p>
                            </ul>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Кракожия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>666-777</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>не дом и не улица</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load catalog_tags %}

<div class="container">
    <div class="row text-center">
        {% for el in data %}
            <div class="col-3">
                <a href="/product/{{ el.id }}" style="text-decoration: none; color: black">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header d-flex align-items-center justify-content-center" style="height: 100px">
                          <h4 class="my-0 font-weight-normal">{{ el.name }}</h4>
                        </div>
                        <div class="card-body">
                            <img src="{{ el.preview|mediapath }}" alt="Превью картинки" style="max-width: 100%;">
                            <h1 class="card-title pricing-card-title">{{ el.price }} денег</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <p>{{ el.description|slice:":50" }}...</p>
                            </ul>
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load catalog_tags %}

<div class="container">
    <div class="row text-center">
        <div class="col-xxl-50">
            <div class="card mb-4 box-shadow">
                <div class="card-header d-flex align-items-center justify-content-center" style="height: 100px">
                  <h4 class="my-0 font-weight-normal">{{ data.name }}</h4>
                </div>
                <div class="card-body">
                    <img src="{{ data.preview|mediapath }}" alt="Превью картинки" style="max-width: 100%; width: 600px; height: 600px">
                    <h1 class="card-title pricing-card-title">{{ data.price }} денег</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <p class="text-center">{{ data.description }}</p>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load catalog_tags %}

    <style>
    .card {
        background-color: #222022;
    }
    form {
        color: white;
    }
    form input[type="text"],
    form textarea {
        width: 100%;
    }
    </style>

    <div class="container">
        <div class="row text-center">
            <div class="col-xxl-50">
                <div class="card mb-4 box-shadow">
                    <form method="post">
                        {% csrf_token %}
                        Удаляем?
                        <input type='submit' class="btn btn-danger" value="Да">
                        <a href="{% url 'blog_list' %}" class="btn btn-primary">Назад</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load catalog_tags %}

<div class="container">
    <div class="row text-center">
        <div class="col-xxl-50">
            <div class="card mb-4 box-shadow">
                <div class="card-header d-flex align-items-center justify-content-center" style="height: 100px">
                  <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <img src="{{ object.preview|mediapath }}" alt="Превью картинки" style="max-width: 100%; width: 600px; height: 600px">
                    <h1 class="card-title pricing-card-title">{{ object.price }} денег</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <p class="text-center">{{ object.description }}</p>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                    {% if user.is_authenticated %}
                        {% if perms.catalog.product_update %}
                            <a href="{% url 'catalog:product_update' pk=object.pk %}" class="btn btn-primary">Редактировать</a>
                        {% endif %}
                        {% if perms.catalog.product_delete %}
                            <a href="{% url 'catalog:product_delete' pk=object.pk %}" class="btn btn-primary">Удалить</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}


<style>
.card {
    background-color: #222022;
}
form {
    color: white;
}
form input[type="text"],
form textarea {
    width: 100%;
}
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="{{ form.name.id_for_label }}">Название товара</label>
                            {{ form.name }}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.description.id_for_label }}">Описание товара</label>
                            {{ form.description }}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.preview.id_for_label }}">Фото товара</label>
                            {{ form.preview }}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.category.id_for_label }}">Категория</label>
                            {{ form.category }}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.price.id_for_label }}">Цена</label>
                            {{ form.price }}
                        </div>
                        <div class="form-group">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                        {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-primary">Назад</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load catalog_tags %}

<div class="container">
    <div class="row text-center">
    {% if user.is_authenticated %}
        <a href="/product/create/" class="btn btn-lg btn-block btn-outline-primary">Добавить новый продукт</a>
    {% endif %}
        {% for el in object_list %}
            <div class="col-3 mt-4">
                <a href="/product/{{ el.id }}" style="text-decoration: none; color: black">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header d-flex align-items-center justify-content-center" style="height: 100px">
                          <h4 class="my-0 font-weight-normal">{{ el.name }}</h4>
                        </div>
                        <div class="card-body">
                            <img src="{{ el.preview|mediapath }}" alt="Превью картинки" style="max-width: 100%;">
                            <h1 class="card-title pricing-card-title">{{ el.price }} денег</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <p>{{ el.description|slice:":50" }}...</p>
                            </ul>
                            {% for version in active_versions %}
                                    {% if version.product == el %}
                                        <p>{{ version.version_name}}</p>
                                    {% endif %}
                            {% endfor %}
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}